app:
  name: airflow-metadata-service
  version: 1.0.1
  environment: development
database:
  host: localhost
  port: 5432
  name: airflow_metadata
  user: admin
  password: changeme
features:
  enable_metrics: true
  enable_backup: false
version: 1.0.1
