app:
  name: airflow-metadata-service
  version: 27bacaf1a4ed3eb0f0c37b22ea81595957f91a59
  environment: development
database:
  host: localhost
  port: 5432
  name: airflow_metadata
  user: admin
  password: changeme
features:
  enable_metrics: true
  enable_backup: false
version: 1.0.1
