app:
  name: airflow-metadata-service
  version: 92dd42f65d62404edeb48a521f545c9035c8d1a0
  environment: development
database:
  host: localhost
  port: 5432
  name: airflow_metadata
  user: admin
  password: changeme
features:
  enable_metrics: true
  enable_backup: false
version: 1.0.1
